name: 'Zephyr deploy summary'
description: 'Create summary of Zephyr deployment'
inputs:
  application_uid:
    description: 'Application UID'
    required: true
  github_token:
    description: 'Enables GitHub Deployments'
    required: false
outputs:
  version_url:
    description: 'URL of deployed version'
runs:
  using: 'node20'
  main: 'index.js'