name: Build and Deploy
on: 
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  build_app:
    runs-on: ubuntu-latest
    environment: development
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: PNPM install
        run: pnpm i
      - name: Build App
        env:
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
          ZE_API: ${{ vars.ZE_API }}
          ZE_API_GATE: ${{ vars.ZE_API_GATE }}
        run: |
          cd zephyr-examples/create-mf-app-rspack
          pnpm i
          pnpm build
      - name: Zephyr deploy summary
        uses: ./ # Uses an action in the root directory
        id: zephyr-summary
        with:
          application_uid: create-mf-app-rspack-host.deploy-summary-action.zephyrcloudio
      - name: Print zephyr deploy summary
        run: echo "Deployed to ${{ steps.zephyr-summary.outputs.version_url }}"

