on: [push]

jobs:
  print_pr_number:
    runs-on: ubuntu-latest
    name: Print PR number
    steps:
      - name: Print PR number
        run: echo "PR number is ${{ github.event.pull_request.number || github.event.number }}"
  build_app:
    runs-on: ubuntu-latest
    environment: development
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM install
        run: npm ci
      - name: Build App
        env:
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
          ZE_API: ${{ vars.ZE_API }}
          ZE_API_GATE: ${{ vars.ZE_API_GATE }}
        run: |
          cd zephyr-examples/create-mf-app-rspack
          npm ci
          npm run build
      - name: Zephyr deploy summary
        uses: ./ # Uses an action in the root directory
        id: zephyr
        with:
          application_uid: create-mf-app-rspack-host.zephyr-ci.opavlovskyi

