on: [push]

jobs:
  zephyr_summary:
    runs-on: ubuntu-latest
    name: Zephyr deploy summary
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM install
        run: npm ci
      - name: Zephyr deploy summary
        uses: ./ # Uses an action in the root directory
        id: zephyr
        with:
          application_uid: 'team-red.zephyr-mono.zephyrcloudio'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          environment: 'development'
      # Use the output from the `zephyr` step
      - name: Get the output version URL
        run: echo "The preview URL - ${{ steps.zephyr.outputs.time }}"
