on: [push]

jobs:
  build_app:
    runs-on: ubuntu-latest
    environment: development
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM install
        run: npm ci
      - name: Build App
        env:
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
          ZE_API: ${{ vars.ZE_API }}
          ZE_API_GATE: ${{ vars.ZE_API_GATE }}
        run: |
          cd zephyr-examples/create-default-webpack-mf
          npm ci
          npm run build
      - name: Debug
        run: |
          echo "ZE_API: ${{ vars.ZE_API }}"
          echo "ZE_API_GATE: ${{ vars.ZE_API_GATE }}"

  zephyr_summary:
    runs-on: ubuntu-latest
    name: Zephyr deploy summary
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM install
        run: npm ci
      - name: Zephyr deploy summary
        uses: ./ # Uses an action in the root directory
        id: zephyr
        with:
          application_uid: default_webpack_mf_first.zephyr-ci.opavlovskyi
          github_token: ${{ secrets.GITHUB_TOKEN }}
          environment: development
      # Use the output from the `zephyr` step
      - name: Get the output version URL
        run: echo "The preview URL - ${{ steps.zephyr.outputs.time }}"
